### ISSUE TITLE
Bug: Recipe with no Ingredients not added to DB but accepted by App

### ISSUE THREAD

**Issue by Tommy-Sand** [CMPUT301F22T02/well-fed#137]
Bug: Attempting to add a recipe with every field filled but with no ingredients will succeed but will this recipe will not be added to the database or be displayed.

 Expected Behaviour: A recipe with no ingredients should not be added at all and the user should be prompted back to add an ingredient.

Steps to reproduce:
1. Click add recipe button
2. Fill in all fields but do not add ingredients
3. Click the save button

**Comment by steventango** [comment]
This issue has been fixed in main.
