### ISSUE TITLE
Bug (? maybe): App still has default string "Hello Akshat" in the meal plan page 

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#145]
We should replace this with something else.

**Comment by steventango** [comment]
So how would we fix this? Implement a new user screen, where on first login we prompt them to give us a name? Implement actual login? (I think it won't be too bad for the demo if we use [FirebaseUI](https://firebase.google.com/docs/auth/android/firebaseui), which gives us one-click login.

**Comment by madisonbradley112** [comment]
> So how would we fix this? Perhaps implement a new user screen, where on first login we prompt them to give us a name? Or just implement actual login? (I think it won't be too bad for the demo if we use [FirebaseUI](https://firebase.google.com/docs/auth/android/firebaseui), which gives us one-click login.

We could just replace it with a generic greeting.
