### ISSUE TITLE
Bug: Recipes: unit & category squashed together/category sometimes doesn't show

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#161]
The unit and category are squashed together after viewing a created recipe
![](https://cdn.discordapp.com/attachments/1015480531644858398/1044047586635567205/Screen_Shot_2022-11-20_at_5.32.17_PM.png)

Steps for replicating:
1. Add a new recipe, with ingredients
2. View the details of that recipe
3. The bug will be visible

And the unit does not show after adding an ingredient to a recipe.
![](https://cdn.discordapp.com/attachments/1015480531644858398/1044047446319321188/Screen_Shot_2022-11-20_at_5.31.42_PM.png)

Steps for replicating:
1. Start the process of adding a new recipe
2. Add a new ingredient to the recipe
3. The bug will be visible

Currently, this makes our instrumented tests for recipe in PR #160 fail (as they check for '1.0 count' and whether the units are visible after adding a recipe). Fixing this bug will make these instrumented tests pass.

**Comment by Manpreet-Singh001** [comment]
@madisonbradley112 is this one fixed?

**Comment by madisonbradley112** [comment]
This has been fixed.
