### ISSUE TITLE
Bug: App crashes on RecipeEditTest

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#182]
Bug: RecipeEditTest fails due to bug with loading in recipes

Likely cause: Since RecipeEditFragment receives an Intent of a Recipe from the RecipeFragment, this intent may contain an old/null version of a Recipe as the RecipeFragment may hold a currently-empty Recipe if it does not get the info from the DB in time. This leads to the app crashing when the user presses the edit button if the Recipe hasn't loaded in yet (visually on screen).

Note: This test fails sometimes, and passes other times. This is due to the variable speed in which Firebase gets the info.

**Comment by madisonbradley112** [comment]
@Manpreet-Singh001 could you take a look at this for me? It's a race condition that may cause our app to crash.

**Comment by Manpreet-Singh001** [comment]
We can just wait for the recipe to load before showing the edit button :) thanks for finding this out.

**Comment by Manpreet-Singh001** [comment]
@madisonbradley112 this one should be fixed can you confirm with latest branch

**Comment by madisonbradley112** [comment]
Confirmed! Thank you!
