### ISSUE TITLE
Bug: Meal Plans do not edit

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#206]
When you try to edit a meal plan, the edit does not go through. 

Steps to replicate:
- Create a meal plan
- Attempt to change some aspect of it
- Save the meal plan
- View the meal plan's info again
- Bug shown, it is the same as before the edit

**Comment by Weiguo-Jiang** [comment]
Based on my observation from DB side, the Ingredients can be edited and the changes will show up in database (inside MealPlan's ArrayList of Ingredients), however this process can take up to 2 seconds and if you click on the MealPlan object right after editing, you will not see the updated version. But if you exit and wait for db to update and then click, the changes (quantity, name of Ingredient, etc) will be shown. However one thing is that you can't seem to view details of an Ingredient in the first Activity (don't know if it's UI issue), for Recipe you can click to see details.
For editing a Recipe, the changes will be shown, but same as Ingredients, it is slow, can take around 2-3s on db. 
The branch I'm on is main.

**Comment by Weiguo-Jiang** [comment]
PS: Changes made to Recipe are all made on DB, basically DB is updating correctly, you can check DB for confirmation. However sometimes it's not updating in the UI.
