### ISSUE TITLE
Bug: Pressing the FAB on Shopping cart causes the app to crash

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#212]
This FAB is not needed currently - maybe we could just remove it here?

Error: java.lang.ClassCastException: com.xffffff.wellfed.shoppingcart.ShoppingCartFragment cannot be cast to com.xffffff.wellfed.common.Launcher

Steps to replicate: 
1. Go to Shopping Cart
2. Press the FAB

<img width="270" alt="Screen Shot 2022-11-24 at 8 23 52 AM" src="https://user-images.githubusercontent.com/90803938/203819299-c6dc5b7e-a7f3-418e-bd48-fdce88e0cba2.png">

**Comment by steventango** [comment]
No, we intend shopping cart to be automatic, this fab should be hidden.
