### ISSUE TITLE
Bug: Trying to edit recipe created by a MealPlan leads to a crash

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#215]
Steps to replicate:

1. Start creating a new MealPlan
2. Add a new recipe with a new ingredient through the MealPlan
3. Click on the new recipe created in the Recipe Book
4. Click the edit button on this recipe
5. App crash occurs

**Comment by Manpreet-Singh001** [comment]
This crashes with any editing @AkshatPandey1 you can start working on it. branch off of main and start your work

**Comment by AkshatPandey1** [comment]
@Manpreet-Singh001 @steventango have either of you guys fixed this issue since it seems to be working on the main branch?

**Comment by steventango** [comment]
This issue is still not working on main branch, we should take a second look at this after #210 is fixed as per @Manpreet-Singh001 's comment
