### ISSUE TITLE
CRC Cards: Recipe

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#22]
# Related issues
[#7](https://github.com/CMPUT301F22T02/well-fed/issues/7)

# Acceptance Criteria
- [x] Object-oriented.
- [x] Cohesive classes.
- [x] Coupling managed.
- [x] Clear, readable, consistent, and organized.
- [x] Cover key classes.
- [x] Complete responsibilities. 
- [x] Complete collaborators.
- [x] Class names conform to encapsulation. Class names should not contain implementation details (For example, "ShoppingCart" is a better class name than "ShoppingList")
- [x] Class names are not plural. (For example, "Ingredients" should be renamed "Ingredient")
- [x] UI class mentions validates user input.
- [x] UI class is has class name with Activity. (For example, "RecipeUI" should be renamed to "RecipeActivity"
- [x] Has multiple UI classes, if applicable. (For example, "RecipeActivity" and "RecipeListActivity")
- [x] Controller class mentions validate complex user input, if applicable.
- [x] Lists of objects are managed in the controller class. (For example, list of recipes goes into RecipeController)
- [x] DB class mentions {store, remove, update} in *Firebase*.
- [x] Model layer class name does not contain "Model". (For example, RecipeModel should be renamed Recipe)
- [x] Model layer class responsibilities uses "keeps" instead of "store"
- [x] Add CRC card into Github Wiki.

**Comment by Tommy-Sand** [comment]
I think there should be a RecipeListActivity like class (not called this exactly) but a class for viewing the list of recipes

**Comment by Manpreet-Singh001** [comment]
> I think there should be a RecipeListActivity like class (not called this exactly) but a class for viewing the list of recipes

Yes, you are correct, i will be adding it. 😄

**Comment by Manpreet-Singh001** [comment]
what should the name of the RecipeListActivity should be since our TA mentioned not to use `List` in our class name, i was thinking `RecipesActivity`.

**Comment by Manpreet-Singh001** [comment]
### RecipeActivity
<html><body>


Responsibilities | Collaborators
-- | --
Adds a recipe to the list of the recipes and updates RecipeDB and RecipeActivity to reflect the changes. | Recipe
Sort the list of recipes by title, preparation time, number of servings, or category. | RecipeDB
Add/Delete an ingredient to a recipe and update RecipeDB and RecipeActivity to reflect the changes. | RecipeActivity


</body>
</html>
Will the RecipeActivity have Recipe as it's collaborator? Since it will use the data stored in it?

**Comment by Manpreet-Singh001** [comment]
Should the recipe be able to create a new ingredient? or only allow already existing ingredients?

**Comment by steventango** [comment]
It should, our current storyboard design allows for that.

**Comment by Manpreet-Singh001** [comment]
> It should, our current storyboard design allows for that.

Our storyboard has a search functionality, what is the functionality searching cause we are only adding the ingredient that this recipe requires. It shouldn't matter if the recipe is in the IngredientStorage.

**Comment by steventango** [comment]
Functionality is using the description and category of a already existing ingredient

**Comment by steventango** [comment]
@Manpreet-Singh001 need a `EditRecipeAcitvity`

**Comment by Manpreet-Singh001** [comment]
> @Manpreet-Singh001 need a `EditRecipeAcitvity`

done

**Comment by Manpreet-Singh001** [comment]
> @Manpreet-Singh001 need a `EditRecipeAcitvity`

where are we storing the already existing ingredient?

**Comment by steventango** [comment]
Not sure.. "IngredientDatabase"?

**Comment by Tommy-Sand** [comment]
![Image](https://user-images.githubusercontent.com/84103219/195947399-23ae443e-713e-4bcc-89c5-a8ff0ebaa00d.png)

I'm going to remove the last responsibility just because the controller already has that responsibility in the RecipeController

**Comment by Manpreet-Singh001** [comment]
> ![Image](https://user-images.githubusercontent.com/84103219/195947399-23ae443e-713e-4bcc-89c5-a8ff0ebaa00d.png)
> 
> I'm going to remove the last responsibility just because the controller already has that responsibility in the RecipeController

the controller will use this functionality on db to perform this task so it should stay :)

**Comment by Tommy-Sand** [comment]
Alright
