### ISSUE TITLE
Bug: Updating a meal plan's recipe will lead to nothing being updated

### ISSUE THREAD

**Issue by Tommy-Sand** [CMPUT301F22T02/well-fed#225]
Steps to replicate
1. Create a MealPlan
2. Edit the MealPlan including any edit to the Recipes of the MealPlan
3. Save the MealPlan

Expected result: The edits are applied to the MealPlan

Actual result: No change to any aspect of the MealPlan is made

**Comment by steventango** [comment]
This works in `main`, but there is a minor race condition noted by #222 that remains.
