### ISSUE TITLE
Address Feedback: Project Part 3 - Addressing Feedback

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#226]
# Feedback
## Score
3/3

## Comment
CRC cards not updated as per feedback.

**Comment by Weiguo-Jiang** [comment]
We will keep our CRC card consistent with the app by part 4.

**Comment by madisonbradley112** [comment]
The CRC was updated according to TA feedback for part 3: 

Feedback given:

> Comments: ShoppingCart Activitiy has one of the responsibilities as list of ingredients but I cannot find Ingredients or IngredientStorage in the collaborator. I see Recipe has Ingredient as one of the collaborators, a good practice will be to have Ingredient Storage as the collaborator because ideally recipie will have multiple ingredients. Why does recipe only have ingredients in its collaborator, recipe book should also be in the collaborators. A class for database connection should be added for the sepearation of concern

Response made:

> 

> To respond to your comments:
> 
> We have added Ingredients as a collaborator to the ShoppingCart. Please note that any reference to an "IngredientStorage" does not refer to any object that holds an Ingredient, but instead the part of the app that holds the user's inventory of Ingredients in their real-life storage. So, a list of ingredients works.
> 
> A recipe is able contain multiple ingredients, in a list attribute. Again, IngredientStorage does not refer to anything that contains ingredients, but specifically used to represent real-life storage of ingredients that a user has.
> 
> To address recipe only having ingredients as a collaborator: We assumed collaboration goes one way. The RecipeBookActivity and the RecipeController should collaborate with ecipe by having many recipes contained and displayed in it, but a single 
> Recipe does not necessarily need to know anything at all about the RecipeBookActivity or Controller - it does not rely on the RecipeBookActivity for anything, or need anything from it. So, a single Recipe does not collaborate with a RecipeBookActivity, but the RecipeBookActivity must collaborate with the Recipe by displaying the Recipes.
> 
> We will add a class for database connection to maintain separation of concerns.

Changes made: 
![image](https://user-images.githubusercontent.com/90803938/203891611-81bcdf47-709b-4694-a735-f4890725a22d.png)
![image](https://user-images.githubusercontent.com/90803938/203891628-74e2b946-e100-4a8e-b950-16830c0d0bdb.png)
![image](https://user-images.githubusercontent.com/90803938/203891639-d0ff9eaf-cc02-4e25-b612-71255d785dc9.png)
![image](https://user-images.githubusercontent.com/90803938/203891651-19b0e33b-d046-4f1d-a107-d9f98d7c5578.png)

We did not fully make the other changes, for the explained reasoning in my response. We hope these reasons were sufficient.
