### ISSUE TITLE
Address Feedback: Project Part 3 - User Interface Mockup and Storyboard

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#227]
# Feedback
## Score
3/3

## Comment
UI works fine. Make sure the UI and storyboards are consistent.

**Comment by steventango** [comment]
# Response to Feedback
Thank you for your feedback. We will make sure that the UI and the storyboard is consistent for Project Part 4.

**Comment by madisonbradley112** [comment]
Storyboard is consistent now.
