### ISSUE TITLE
Address Feedback: Project Part 3 - Relative Quality

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#231]
# Feedback
## Score
3/3

## Comment
- data is realistic
- github actions
- hosting javadoc
- material components
- add sorting for part 4

**Comment by steventango** [comment]
Thank you for the feedback on our relative quality. We have already implemented sorting for Project Part 4. We will continue to deliver outstanding relative quality in Project Part 4.
