### ISSUE TITLE
Address Feedback: Project Part 3 - Code Base

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#232]
# Feedback
## Score
3/3

## Comment
• Excellent Code base.
• More than ½ of requirements implemented and fully done
• Comprehensive connectivity to server
• Code is clear
• Readable
• Useful comments
• Checks for errors
• Follows conventions

Overall, the code base is well planned

**Comment by Manpreet-Singh001** [comment]
Thank you for the feedback, we will try our best to stick to these standards
