### ISSUE TITLE
Address Feedback: Project Part 3 - Code Documentation

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#233]
# Feedback
## Score
3/3

## Comment
• Codes are easily understandable.
• Complete and correct Javadoc comments for entity (model) classes and methods
• Consistent with requirements, design, code, and tests

Tests are comprehensive and consistent with the code and test coverage is excellent.

**Comment by AkshatPandey1** [comment]
Thank you for the feedback regarding the code documentation. We even have it hosted on GitHub pages if you would like to view it without opening it through the directories. You can find the link on the main page of the repository :) We'll continue to keep it this way.
