### ISSUE TITLE
Address Feedback: Project Part 3 - Product Backlog

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#234]
# Feedback
## Score
2/3

## Comment
• Numbered, tracked, and organized requirements
• Comprehensive requirements
• Complete story point estimates
• Complete risk levels
• Displays understanding of requirements specification/elicitation
X There is a section of the sprint for the half-way checkpoint, but no issues are tagged as such.

**Comment by Manpreet-Singh001** [comment]
We did mark the issues as half-way checkpoint, so I believe the TAs missed something.

**Comment by madisonbradley112** [comment]
I have added checkmarks to the Part 3 product backlog with the issues that were marked as half way checkpoint, just to be extra clear.
