### ISSUE TITLE
Address Feedback: Project Part 3 - Object-Oriented Design

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#235]
# Feedback
## Score
1/3

## Comment
Good job in making UML readable and consistent to the codebase. A few improvements which can be improved on are, please avoid adding the button and edit text in the UML diagram as it makes takes up space and makes it less readable. While going thhrough the code base it does not seem consistent because There are 2 different java files named IngredientStorageController, StorageIngredients.java please have the names consistent and refactor in the next submission. StoredIngredientDB and DeleteDialog Fragment are not connected tot he UML diagram wso what is the purpose of them ? The same goes for ShoppingCartDB I see IngredientController in UML but am not able to find it in the codebase inside Ingredientfolder please make it consistent.

**Comment by Tommy-Sand** [comment]
For the Object Oriented Design, we lost 2 marks however considering the inconsistencies were minor we believe the code base and UML deserve a higher mark. We believe you were comparing the UML to a newer codebase then the deadline. Looking at commit b756783ef6116bec3fba7486665f32728a3b4b7f. Regarding the consistency of file names there is no IngredientStorageController (but there is a IngredientStorageFragment), but IngredientStorageFragment is different from StorageIngredient files, IngredientStorageFragment is for viewing the list of StoredIngredients. IngredientController is present in the ingredient folder in this commit. Regarding shopping cart not being connected in the UML diagram, at the time it was not currently integrated with the rest of shopping cart but was still being worked on.

With regards to some of the classes not being connected to the UML, this will be fixed and was an oversight on my part.

We will also remove the TextViews, Buttons, InputTexts, etc from UI classes in the final UML to improve readability
