### ISSUE TITLE
CRC Cards: MealPlan

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#24]
# Related issues
[#15](https://github.com/CMPUT301F22T02/well-fed/issues/15)

# Acceptance Criteria
- [x] Object-oriented.
- [x] Cohesive classes.
- [x] Coupling managed.
- [x] Clear, readable, consistent, and organized.
- [x] Cover key classes.
- [x] Complete responsibilities. 
- [x] Complete collaborators.
- [x] Class names conform to encapsulation. Class names should not contain implementation details (For example, "ShoppingCart" is a better class name than "ShoppingList")
- [x] Class names are not plural. (For example, "Ingredients" should be renamed "Ingredient")
- [x] UI class mentions validates user input.
- [x] UI class is has class name with Activity. (For example, "RecipeUI" should be renamed to "RecipeActivity"
- [x] Has multiple UI classes, if applicable. (For example, "RecipeActivity" and "RecipeListActivity")
- [x] Controller class mentions validate complex user input, if applicable.
- [x] Lists of objects are managed in the controller class. (For example, list of recipes goes into RecipeController)
- [x] DB class mentions {store, remove, update} in *Firebase*.
- [x] Model layer class name does not contain "Model". (For example, RecipeModel should be renamed Recipe)
- [x] Model layer class responsibilities uses "keeps" instead of "store"
- [x] Add CRC card into Github Wiki.

**Comment by madisonbradley112** [comment]
should I have 2 entity classes - one for Meal, and one for MealPlan? i was thinking that a MealPlan would hold a list of meals and also contain information on the date that a meal is being eaten on,... but also a meal could just keep that info on its own

**Comment by Manpreet-Singh001** [comment]
@madisonbradley112 i had the same design, but our as TA mentioned today, since the logic for list won't be that complicated we won't need a different class for it. We can just have a list that stores meal, where we can edit/add meals to the list via the Controller class. Hope this helps 👍 .

**Comment by Manpreet-Singh001** [comment]
@madisonbradley112 i had the same design, but our as TA mentioned today, since the logic for list won't be that complicated we won't need a different class for it. We can just have a list that stores meal, where we can edit/add meals to the list via the Controller class. Hope this helps 👍 .

**Comment by madisonbradley112** [comment]
<img width="844" alt="Screen Shot 2022-10-14 at 12 16 19 AM" src="https://user-images.githubusercontent.com/90803938/195775681-fc06eb6e-a612-4e08-95d8-ae79997d1e72.png">
<img width="849" alt="Screen Shot 2022-10-14 at 12 16 50 AM" src="https://user-images.githubusercontent.com/90803938/195775756-a4e3827f-f7be-4f9a-8248-356e8b4eef84.png">


I have my first draft for the CRC cards for Meal. I'm a little uncertain about some of my choices - can someone suggest changes/additions/things I may have missed? A little uncertain about what "business logic" refers to in the context of a Meal, too.

**Comment by Manpreet-Singh001** [comment]
* Rename MealUI to MealActivity.
For the points that say add/edit values, i am not sure but are we handling that functionality in the UI class @steventango @AkshatPandey1 ? cause i think these fields will just exist there and take input, handling it will be done in the controller class right?

**Comment by Manpreet-Singh001** [comment]
> <img alt="Screen Shot 2022-10-14 at 12 16 19 AM" width="844" src="https://user-images.githubusercontent.com/90803938/195775681-fc06eb6e-a612-4e08-95d8-ae79997d1e72.png">
> 
> <img alt="Screen Shot 2022-10-14 at 12 16 50 AM" width="849" src="https://user-images.githubusercontent.com/90803938/195775756-a4e3827f-f7be-4f9a-8248-356e8b4eef84.png">
> 
> I have my first draft for the CRC cards for Meal. I'm a little uncertain about some of my choices - can someone suggest changes/additions/things I may have missed? A little uncertain about what "business logic" refers to in the context of a Meal, too.
> 
> Edit: Oops, forgot to note the list of requirements. Will make those ASAP - any suggestions on what "complete collaborators" and "complete responsibilities" entails (also, "coupling managed" )

## MealController
* instead of using `Tells` maybe more clear would be `Update DB to reflect changes`?
* it won't get the data from the UI itself but rather from the Model Class. 
* to make the last point in your crc clearer, maybe some wording like `Gets Meals from MealDB and updates....

**Comment by Manpreet-Singh001** [comment]
> <img alt="Screen Shot 2022-10-14 at 12 16 19 AM" width="844" src="https://user-images.githubusercontent.com/90803938/195775681-fc06eb6e-a612-4e08-95d8-ae79997d1e72.png">
> 
> <img alt="Screen Shot 2022-10-14 at 12 16 50 AM" width="849" src="https://user-images.githubusercontent.com/90803938/195775756-a4e3827f-f7be-4f9a-8248-356e8b4eef84.png">
> 
> I have my first draft for the CRC cards for Meal. I'm a little uncertain about some of my choices - can someone suggest changes/additions/things I may have missed? A little uncertain about what "business logic" refers to in the context of a Meal, too.
> 
> Edit: Oops, forgot to note the list of requirements. Will make those ASAP - any suggestions on what "complete collaborators" and "complete responsibilities" entails (also, "coupling managed" )

### MealDB
in the responsibilities, i am seeing some business logic which i think would be better handled by the controller itself. for example:
> Gets user-updated Meals from MealController and updates Meals stored in firebase database.
the class shouldn't be concerned with how it got the data or where it got the data, it should only be concerned with performing the operation which is updating the data in database.

**Comment by steventango** [comment]
| Our TA asked us to change the store with has since store can be confused with storing it somewhere [ i m not sure about it, but i am confirming it with @steventango and @AkshatPandey1 right now]

To clarify, the TA stated that in entity classes, we should be using class "keeps" an attribute (Example: the Ingredient class keeps a location. Whereas, the DB class "stores" an attribute in Firestore (Example: the IngredientDB class stores a location in Firestore).

**Comment by steventango** [comment]
> For the points that say add/edit values, i am not sure but are we handling that functionality in the UI class @steventango @AkshatPandey1 ? cause i think these fields will just exist there and take input, handling it will be done in the controller class right?

Should be UI class. UI class also does simple input validation. Controller class is for business logic, not read/write EditText.

**Comment by steventango** [comment]
@madisonbradley112 rename "Meal" to "MealPlan" and so on, we don't have "Meal" class, we have "MealPlan" class.

**Comment by steventango** [comment]
@madisonbradley112 rename "Meal" to "MealPlan" and so on, we don't have "Meal" class, we have "MealPlan" class.

**Comment by madisonbradley112** [comment]
@AkshatPandey1 @steventango could you change Meal to MealPlan for me in the CRC card wiki page, and come up with a reasonable new class name for the Activity that displays all MealPlans (currently MealPlanActivity)? I don't have much time today to make these small changes, so it would be greatly appreciated!

**Comment by steventango** [comment]
Okay

**Comment by madisonbradley112** [comment]
> Okay

Actually, I found some time - doing this right away.

**Comment by Weiguo-Jiang** [comment]
Since Meal changes to MealPlan, I'll update my collaborators accordingly.

**Comment by Manpreet-Singh001** [comment]
<html><body>
<h3>MealPlanActivity</h3>


Responsibilities | Collaborators
-- | --
Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients | MealPlanController
Takes input from a user that indicates serving size of the new MealPlan |  
Upon user confirmation, sends new MealPlan information to MealPlanController |  


</body>
</html>
<html><body>
<h3><a id="user-content-mealplanaddactivity" class="anchor" aria-hidden="true" href="https://github.com/CMPUT301F22T02/well-fed/wiki/Part-2:-CRC-Cards#mealplanaddactivity"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a>MealPlanAddActivity</h3>


Responsibilities | Collaborators
-- | --
Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients | MealPlanController
Takes input from a user that indicates serving size of the new MealPlan | MealPlan
Upon user confirmation, sends new Meal information to MealPlanController |  


</body>
</html>
<br>
What is the difference between these two?

**Comment by madisonbradley112** [comment]
> ### MealPlanActivity
> Responsibilities	Collaborators
> Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients	MealPlanController
> Takes input from a user that indicates serving size of the new MealPlan	 
> Upon user confirmation, sends new MealPlan information to MealPlanController	 
> ### MealPlanAddActivity
> Responsibilities	Collaborators
> Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients	MealPlanController
> Takes input from a user that indicates serving size of the new MealPlan	MealPlan
> Upon user confirmation, sends new Meal information to MealPlanController	 
> 
> What is the difference between these two?

I wanted to match the storyboard, so I included storyboard screenshots below.

My intention was to have one screen that shows detailed information about the MealPlan (no adding)
<img width="180" alt="Screen Shot 2022-10-14 at 2 06 18 PM" src="https://user-images.githubusercontent.com/90803938/195932953-5e5362c5-75a2-47de-a280-c35fded03687.png">


and a completely different screen that allows the user to add info: 
<img width="182" alt="Screen Shot 2022-10-14 at 2 07 14 PM" src="https://user-images.githubusercontent.com/90803938/195933099-4e7b8a71-5abb-479f-9fa1-3aa901ecf56d.png">



 Do you have any suggestions on how I could make this clearer?

**Comment by Manpreet-Singh001** [comment]
> > ### MealPlanActivity
> > Responsibilities	Collaborators
> > Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients	MealPlanController
> > Takes input from a user that indicates serving size of the new MealPlan	 
> > Upon user confirmation, sends new MealPlan information to MealPlanController	 
> > ### MealPlanAddActivity
> > Responsibilities	Collaborators
> > Takes input from a user that indicates a new MealPlan, with selected recipes and ingredients	MealPlanController
> > Takes input from a user that indicates serving size of the new MealPlan	MealPlan
> > Upon user confirmation, sends new Meal information to MealPlanController	 
> > What is the difference between these two?
> 
> I wanted to match the storyboard, so I included storyboard screenshots below.
> 
> My intention was to have one screen that shows detailed information about the MealPlan (no adding) <img alt="Screen Shot 2022-10-14 at 2 06 18 PM" width="180" src="https://user-images.githubusercontent.com/90803938/195932953-5e5362c5-75a2-47de-a280-c35fded03687.png">
> 
> and a completely different screen that allows the user to add info: <img alt="Screen Shot 2022-10-14 at 2 07 14 PM" width="182" src="https://user-images.githubusercontent.com/90803938/195933099-4e7b8a71-5abb-479f-9fa1-3aa901ecf56d.png">
> 
> Do you have any suggestions on how I could make this clearer?

What i am seeing is that the first screen only displays details of the meal plan and only receives input for deleting/editing the mealplan. So, changing the responsibilities to these would make it more clearer.

**Comment by madisonbradley112** [comment]
Oh, oops, didn't realize I duplicated them! Will change ASAP

**Comment by AkshatPandey1** [comment]
Is the card finished?

**Comment by steventango** [comment]
LGTM
