### ISSUE TITLE
Bug: Edit Meal Plan add multiple copies of the same Recipe broken

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#245]
1. Create Meal Plan with Recipe R
2. Edit Meal Plan, add multiple copies of Recipe R
3. Nothing happens. Meal Plan update callback never called

**Comment by Weiguo-Jiang** [comment]
After debugging, the problem not only exist with duplicate Recipes but also distinct Recipes. The reason is that newly added Recipes have every other field null except ID, which failed on the updateRecipe() method.

**Comment by Manpreet-Singh001** [comment]
This issue was caused by RecipeProxy Optimization
