### ISSUE TITLE
Bug: Adding 7 ingredients and then sorting sometimes swaps ingredients with each other

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#249]
I have 7 ingredients, but only 6 are shown at one time, and two of them swap out depending on what I sort by. I can search for both even if they don't show up in the list.

(Here, tortilla and cereal swap out)

![Screenshot_1669442273](https://user-images.githubusercontent.com/90803938/204074702-e9289362-3303-43a9-b96b-b1356b40974d.png)

![Screenshot_1669442097](https://user-images.githubusercontent.com/90803938/204074729-20f2f8a8-eda3-4b7b-9250-76871b6cabf1.png)

**Comment by madisonbradley112** [comment]
Note: It is the last element in the list, always.

**Comment by Manpreet-Singh001** [comment]
Seems like a padding issue.

**Comment by Weiguo-Jiang** [comment]
This one is solved by Steven already, see chat history.
