### ISSUE TITLE
CRC Cards: Ingredient

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#25]
# Related issues
[#1](https://github.com/CMPUT301F22T02/well-fed/issues/15)

# Acceptance Criteria
- [x] Object-oriented.
- [x] Cohesive classes.
- [x] Coupling managed.
- [x] Clear, readable, consistent, and organized.
- [x] Cover key classes.
- [x] Complete responsibilities. 
- [x] Complete collaborators.
- [x] Class names conform to encapsulation. Class names should not contain implementation details (For example, "ShoppingCart" is a better class name than "ShoppingList")
- [x] Class names are not plural. (For example, "Ingredients" should be renamed "Ingredient")
- [x] UI class mentions validates user input.
- [x] UI class is has class name with Activity. (For example, "RecipeUI" should be renamed to "RecipeActivity"
- [x] Has multiple UI classes, if applicable. (For example, "RecipeActivity" and "RecipeListActivity")
- [x] Controller class mentions validate complex user input, if applicable.
- [x] Lists of objects are managed in the controller class. (For example, list of recipes goes into RecipeController)
- [x] DB class mentions {store, remove, update} in *Firebase*.
- [x] Model layer class name does not contain "Model". (For example, RecipeModel should be renamed Recipe)
- [x] Model layer class responsibilities uses "keeps" instead of "store"
- [x] Add CRC card into Github Wiki.

**Comment by steventango** [comment]
Need to remove or clarify "IngredientList" in CRC cards.

**Comment by Tommy-Sand** [comment]
I've made the relevant changes

**Comment by AkshatPandey1** [comment]
@Tommy-Sand I'm not sure you've made those changes yet

![image](https://user-images.githubusercontent.com/71156802/195912519-9b7d117e-78ff-47ee-882c-f5d160465859.png)

**Comment by Tommy-Sand** [comment]
Sorry I think I misunderstood Steven's comment, I'll fix it

**Comment by Tommy-Sand** [comment]
So I modified it to now look like this.

![Image](https://user-images.githubusercontent.com/84103219/195915261-1231fff2-23b6-4227-a296-c8150b9cd77a.png)



![Image](https://user-images.githubusercontent.com/84103219/195915339-60763ecf-8181-4a96-992c-66b06855fabe.png)

**Comment by steventango** [comment]
@AkshatPandey1 @Weiguo-Jiang just want to clarify if TA is okay with "Get the most current brief description for every Ingredient in the IngredientList from IngredientDB", or if that doesn't count as "business logic"? I recall him elaborating on it, but don't remember the details.

**Comment by Tommy-Sand** [comment]
I think since it's there only for IngredientList it makes sense to have it there since the TA said that any list would be in the controller

I have it as IngredientStorageControler, I thought it made sense since it's there for both the IngredientStorageActivity and IngredientActivity, and it also stores all the ingredients in IngredientList

**Comment by Weiguo-Jiang** [comment]
I'd say IngredientStorageController since IngredientController refers to a single Ingredient object and we are suppose to display a list of Ingredient objects.

**Comment by madisonbradley112** [comment]
Does Ingredient necessarily collaborate with IngredientStorageController? I think the collaboration is one-way here.

**Comment by Tommy-Sand** [comment]
You're right, I'll remove IngredientStorageController there and some other ingredient classes have collaborators that should be removed

**Comment by steventango** [comment]
@Tommy-Sand can we get a `IngredientEditActivity`

**Comment by Tommy-Sand** [comment]
Sure

**Comment by Tommy-Sand** [comment]
Actually I think the current IngredientActivity functions as a IngredientEditActivity, so I can just create a new IngredientActivity and the old one can be the IngredientEditActivity

**Comment by Tommy-Sand** [comment]
@steventango So I just turned IngredientActivity into IngredientEditActivity and the new IngredientActivity  is a stripped down version of the old IngredientActivity but that allows the user to goto IngredientEditActivity to edit the ingredient.

**Comment by steventango** [comment]
LGTM
