### ISSUE TITLE
UI: Setup UI for Ingredients

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#47]
#2 #3 #4  #5 Setup basic functionality for these stories.

**Comment by Manpreet-Singh001** [comment]
@AkshatPandey1 do you wanna work with #5 since it is bit tedious chore and maybe we can assign #5 to other people :)

**Comment by AkshatPandey1** [comment]
I mean, #5 is directly related to what I'm doing, I think I'll be fine with it

**Comment by Manpreet-Singh001** [comment]
#5 requires creating Contracts since it will be working with different intents, we have also decided to not have a search feature right now as discussed by @Tommy-Sand @madisonbradley112

**Comment by madisonbradley112** [comment]
Akshat has set up the UI for these stories.
