### ISSUE TITLE
DB: Design a basic schema choice for the various collections.

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#48]

**Comment by Manpreet-Singh001** [comment]
@madisonbradley112 will get a rough draft by 19 Wednesday 2022

**Comment by Manpreet-Singh001** [comment]
schema proposal for ingredients
```
ingredient
- description
- name?
- category
- unit
```

```
storedIngredient
- ingredient
- location
- best before date
- amount
```
this will allow us to have ingredient as an entity of it's own that can interact with Recipe and ShoppingList. 

### why is this needed?
let's say we store a banana in the freezer and another banana on the shelf. recipe isn't concerned with where the banana is stored, it is only concerned with the ingredient itself i.e. the banana. it isn't concerned with the amount of banana we have it is only concerned with the how many it needs.

**Comment by madisonbradley112** [comment]
Are user shopping cart states consistent across app runs? Will we have to include a shopping cart state in DB? Currently, our CRC design just states that the shopping cart updates ingredients.

**Comment by Tommy-Sand** [comment]
Could you elaborate on what a shopping cart state is?

**Comment by madisonbradley112** [comment]
Schema proposal, for all collections. The title in each code block is the collection, and the fields below are fields required for any document in that collection. Can I request someone review this schema, and raise any concerns?

```
Ingredient 
- category : string
- description/name : string
```

```
StoredIngredient 
- ingredient : reference to object in the Ingredient collection
- location : string
- best-before : timestamp
- amount-stored : number
- unit-stored : string
```

```
RecipeorMealIngredient 
- ingredient : reference to object in the Ingredient collection
- amount : number
- unit : string
```

```
ShoppingCartIngredient
- ingredient : reference to object in the Ingredient collection
- is-picked-up : boolean
- amount-obtained : number
- unit-obtained : string
```

```
Recipe 
- title : string
- category : string
- comments : string
- servings : number
- prep-time-minutes : number
- photograph : string that is a valid image link (can we host images in firestore?)
- ingredients-recipe : array of references to objects in the RecipeorMealIngredient collection
```

```
MealPlan 
- title : string
- ingredients-meal : array of references to objects in the RecipeorMealIngredient collection
- recipes : array of references to objects in the Recipe collection
- eat-date : timestamp
```

```
ShoppingCart
- ingredients-cart : array of references to objects in the ShoppingCartIngredient collection
```

**Comment by madisonbradley112** [comment]
> Could you elaborate on what a shopping cart state is?

A shopping cart state would include all of the ingredients within a shopping cart at any given point of time. I was thinking of including it in the database, as if we ever have separate users of the app, we will need to keep track of their shopping carts individually. This would allow the user to return to their shopping cart (almost using it as a to-do list) for future runs of the app.

**Comment by Tommy-Sand** [comment]
I think we should just keep track of all items in the shopping cart but we don't need to store seperate shopping cart states since if multple users use the app then we might want to make a collection of users each with a subcollection for their ingredients, recipies, shoppingcart, mealplan, etc.

**Comment by steventango** [comment]
In the case that shopping carts could be shared between users, wouldn't it be valuable to not make the shopping cart state exclusive to each user. For example, a house with two users, may want to share shopping carts / ingredient storages?

**Comment by Manpreet-Singh001** [comment]
Yes, I agree with @steventango , we will not nest the shopping cart withing a user.
Reason:
It will make querying really hard and inefficient, let's say a user has 100 ingredients in their shopping cart and they want to update one of them, our query would have to loop through the array to find a match, then update it, which is very inefficient.

**Comment by Tommy-Sand** [comment]
@Manpreet-Singh001
How is your reasoning exclusive to nesting within a user since wouldn't you be searching regardless of whether it's nested in a collection or not? For clarification though, I suggested nesting within a user for cases where you had multiple people not within the same house but this isn't something that we need or can easily implement.

**Comment by Manpreet-Singh001** [comment]
> @Manpreet-Singh001 How is your reasoning exclusive to nesting within a user since wouldn't you be searching regardless of whether it's nested in a collection or not? For clarification though, I suggested nesting within a user for cases where you had multiple people not within the same house but this isn't something that we need or can easily implement.

Example with nesting: 
```
UserA:
           Ingredients
           Shopping List:
              Ingredients in shopping list let's say [ig1, ig2, ig3, ig4]
```
now if user wants to update one of the ingredient let's say `ig4`  in shopping list the process would be like, find UserA->find shoppingList->
loop through all the ingredients in shopping list and find the one that needs updating, since it is subnested withing shopping list we cannot access `ig4` directly.

what i am suggesting is a flat document structure like
``` 
ShoppingList collection:
    ig1 which is a document that contains the user it belongs to 
    ig2
    ig3
    ig4
```
this will make querying easier it would be as simple as update `ig4` whose `uid = manpreeeeeeeeet`
hope this clarifies it :)

**Comment by madisonbradley112** [comment]
One issue I am coming across is how an image should be stored in DB. Does anyone have any ideas?

**Comment by steventango** [comment]
Consider using https://firebase.google.com/docs/storage

**Comment by madisonbradley112** [comment]
How do we plan on identifying an item in DB? Firestore provides auto-generated IDs, but I am finding that this might be inconvenient if we choose to query for an item by ID from the DB.
