### ISSUE TITLE
UI: Setup for Meal Plan

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#50]
we need a basic ui/activity page for the meal plan. #15 
@steventango @Weiguo-Jiang can you one of you guys self assign it to yourself. :)

**Comment by steventango** [comment]
![image](https://user-images.githubusercontent.com/18170455/199370270-16ba12cb-f43e-43d7-bc92-2c305535c6a2.png)
We should refactor the wording in our mealplan code
mealplan = mealbook, meal = mealplan, ...

**Comment by madisonbradley112** [comment]
Steven has created the UI for this.
