### ISSUE TITLE
DB: set up methods for connecting to + querying the database

### ISSUE THREAD

**Issue by madisonbradley112** [CMPUT301F22T02/well-fed#61]
We should set up methods for connecting to and querying the database.

**Comment by madisonbradley112** [comment]
1. Should the database, when queried, return a created object, or should it return the fields individually?

**Comment by Weiguo-Jiang** [comment]
I think probably an object for encapsulation purposes and good OO practice.

**Comment by madisonbradley112** [comment]
This has been completed.
