### ISSUE TITLE
Bug: UI the icons fail to update their tint to green on swiping.

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#64]
![image](https://user-images.githubusercontent.com/93985396/196869151-5a0ba473-56fb-4e8b-9304-bf41c83128f9.png)
expected behavior: the bottom menu should turn the selected icon to blue color.
steps to reproduce:
swipe to a different screen

**Comment by Tommy-Sand** [comment]
I'm assigning myself to this issue I have a fix ready
