### ISSUE TITLE
Discussion: What kind of layout should we use? (constraint, linear, relative, etc)

### ISSUE THREAD

**Issue by Weiguo-Jiang** [CMPUT301F22T02/well-fed#70]

**Comment by Manpreet-Singh001** [comment]
I personally prefer constraint layout and would like to use it atleast for my part of UI :)

**Comment by madisonbradley112** [comment]
> I personally prefer constraint layout and would like to use it atleast for my part of UI :)

I prefer constraint layout as well - for me, it is simpler to use.

**Comment by AkshatPandey1** [comment]
Ong same, constraint layout OP.

**Comment by steventango** [comment]
Okay, let's try to use constraint layout.
