### ISSUE TITLE
Project Part-02 Scores

### ISSUE THREAD

**Issue by AbdulAli** [CMPUT301F22T02/well-fed#87]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | Final   comments
-- | -- | -- | -- | -- | -- | -- | -- | --
Tool Practices | Product   Backlog | Object-Oriented   Analysis | User   Interface Mockup and Storyboard | Other
3 | Good,   start using branches for each issue. | 3 | •   Numbered, tracked, and organized requirements     • Comprehensive requirements     • Complete story point estimates     • Complete risk levels     • Displays understanding of requirements specification/elicitation     • Requirements noted for half-way checkpoint | 2 | •   Clear, readable, consistent, and organized: yes     • Covers key classes: yes     • Complete responsibilities: yes     • Complete collaborators: see comments     • Object-oriented: yes     • Cohesive classes: yes     • Coupling managed: yes     Comments: ShoppingCart Activitiy has one of the responsibilities as list of   ingredients but I cannot find Ingredients or IngredientStorage in the   collaborator. I see Recipe has Ingredient as one of the collaborators, a good   practice will be to have Ingredient Storage as the collaborator because   ideally recipie will have multiple ingredients. Why does recipe only have   ingredients in its collaborator, recipe book should also be in the   collaborators. A class for database connection should be added for the   sepearation of concern | 3 | Excellent.   But it seems like only one person worked. |  

</body>

</html>

**Comment by AbdulAli** [comment]
Hi guys  @steventango  @Weiguo-Jiang  @AkshatPandey1  @Tommy-Sand 
Please tag the other team members as i cant seem to find them on the tagging list.
Please create a separate issue to address each feedback, thanks.

**Comment by steventango** [comment]
@AbdulAli is the table above missing a heading for what each score is for?

@Manpreet-Singh001 @madisonbradley112

**Comment by Manpreet-Singh001** [comment]
> @AbdulAli is the table above missing a heading for what each score is for?
> 
> @Manpreet-Singh001 @madisonbradley112

yes i cannot see what the score is for.

**Comment by AbdulAli** [comment]
To me its visible :S
<img width="772" alt="Screen Shot 2022-10-30 at 11 44 47 AM" src="https://user-images.githubusercontent.com/6480345/198893183-9c0eb38d-c0ae-45c5-93ef-9a9b717525c8.png">

**Comment by steventango** [comment]
We want to know what the comments are referring to @AbdulAli 

For example,
> Excellent. But it seems like only one person worked.

What part of the project does this comment referring to?

**Comment by AbdulAli** [comment]
You still cant see the headings?

**Comment by AkshatPandey1** [comment]
May we know what do you mean by 

> Excellent. But it seems like only one person worked.

Cause we don't know what you're talking about

@AbdulAli

**Comment by Tommy-Sand** [comment]
![image](https://user-images.githubusercontent.com/84103219/198895428-c5c5032b-cec5-483d-a6c2-03773cfae2e1.png)

We can see the header, but there is no description of what each section is reffering to so we are not sure what comment refers to what section.

Such as 

> Excellent. But it seems like only one person worked.

**Comment by AbdulAli** [comment]
My bad. Updated the headings..

**Comment by steventango** [comment]
Please see issues #88 #89 #90 #91 to see our response to the feedback, thanks.
