### ISSUE TITLE
Address Feedback: Project Part 2 - Object Oriented Analysis

### ISSUE THREAD

**Issue by steventango** [CMPUT301F22T02/well-fed#89]
# Feedback: Project Part 2 - Object Oriented Analysis
## Score
2/3

## Comment
* Clear, readable, consistent, and organized: yes 
* Covers key classes: yes 
* Complete responsibilities: yes
* Complete collaborators: see comments
* Object-oriented: yes
* Cohesive classes: yes
* Coupling managed: yes
* Comments: ShoppingCart Activitiy has one of the responsibilities as list of ingredients but I cannot find Ingredients or IngredientStorage in the collaborator. I see Recipe has Ingredient as one of the collaborators, a good practice will be to have Ingredient Storage as the collaborator because ideally recipie will have multiple ingredients. Why does recipe only have ingredients in its collaborator, recipe book should also be in the collaborators. A class for database connection should be added for the sepearation of concern

**Comment by madisonbradley112** [comment]
Thank you for your feedback.

To respond to your comments: 

1. We have added Ingredients as a collaborator to the ShoppingCart. Please note that any reference to an "IngredientStorage" does not refer to any object that holds an Ingredient, but instead the part of the app that holds the user's inventory of Ingredients in their real-life storage. So, a list of ingredients works.

2. A recipe is able contain multiple ingredients, in a list attribute. Again, IngredientStorage does not refer to anything that contains ingredients, but specifically used to represent real-life storage of ingredients that a user has.

3. To address recipe only having ingredients as a collaborator: We assumed collaboration goes one way. The RecipeBookActivity and the RecipeController should collaborate with Recipe by having many recipes contained and displayed in it, but a single Recipe does not necessarily need to know anything at all about the RecipeBookActivity or Controller - it does not rely on the RecipeBookActivity for anything, or need anything from it. So, a single Recipe does not collaborate with a RecipeBookActivity, but the RecipeBookActivity must collaborate with the Recipe by displaying the Recipes. 

4. We will add a class for database connection to maintain separation of concerns.
