### ISSUE TITLE
Mock Data

### ISSUE THREAD

**Issue by Manpreet-Singh001** [CMPUT301F22T02/well-fed#94]
Add classes that allows quick ability to `create/delete` the entire data in our database. This would allow everyone to work with real data and which we can guarantee to be consistent at all times.

**Comment by Manpreet-Singh001** [comment]
I will need someone who has worked on db classes before to work with me on this @madisonbradley112 @Tommy-Sand anyone up to take this with me? Since I cannot proceed without some data.

**Comment by madisonbradley112** [comment]
We might want to be cautious about providing a method that can clear out data from the database that we are likely going to use for production. Would it be feasible to set up a test environment (or maybe even a test user) for this?

**Comment by madisonbradley112** [comment]
We have set up the generation of users, to fill this need.
